CREATE TABLE NEW_EMP2
(NO NUMBER(4) PRIMARY KEY
,NAME VARCHAR(20) NOT NULL
,JUMIN CHAR(13) NOT NULL UNIQUE
,LOC_CODE NUMBER(1) CHECK(LOC_CODE < 5)
,DEPTNO VARCHAR2(6) REFERENCES DEPT2 (DCODE)
);

ALTER TABLE NEW_EMP2
ADD CONSTRAINT
NEW_EMP2_NAME_UK UNIQUE(NAME);


ALTER TABLE NEW_EMP2
MODIFY (LOC_CODE CONSTRAINT NEW_EMP2_LOCCODE_NN NOT NULL);


INSERT INTO NEW_EMP2 VALUES(1001,'홍길동','3312122111555',4,'1011');
INSERT INTO NEW_EMP2 VALUES(1002,'홍길순','4412122111555',4,'1011');
INSERT INTO NEW_EMP2 VALUES(1003,'홍길자','5512122111555',4,'');
INSERT INTO NEW_EMP2 VALUES(1004,'홍길영','6612122111555',4,'1012');

COMMIT;

SELECT * FROM NEW_EMP2;


SELECT * FROM T_NOVALIDATE;

INSERT INTO T_NOVALIDATE VALUES(1, 'DDD');

ALTER TABLE T_NOVALIDATE
DISABLE NOVALIDATE CONSTRAINT SYS_C007037;  -- 제약조건 못쓰게

ALTER TABLE T_NOVALIDATE
ENABLE NOVALIDATE CONSTRAINT SYS_C007037; -- 제약조건 쓰게


DELETE FROM T_NOVALIDATE
WHERE NAME='DDD';


SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMP';



SELECT COLUMN_NAME
  FROM USER_CONS_COLUMNS
  WHERE TABLE_NAME = 'EMP'
  AND CONSTRAINT_NAME = ( SELECT CONSTRAINT_NAME
                          FROM USER_CONSTRAINTS
                          WHERE TABLE_NAME = 'EMP'
                          AND CONSTRAINT_TYPE = 'R');    -- 컬럼의 제약조건을 한번에 검색
  
  
SELECT CONSTRAINT_NAME
  FROM USER_CONSTRAINTS
  WHERE TABLE_NAME = 'EMP'
  AND CONSTRAINT_TYPE = 'P';
  
ALTER TABLE NEW_EMP2
DROP CONSTRAINT
NEW_EMP2_NAME_UK;