CREATE TABLE STUDENT2
(STU_ID CHAR(5) CONSTRAINT STUDENT2_STU_ID_PK PRIMARY KEY
                CONSTRAINT STUDENT2_STU_ID_CK CHECK(LENGTH(TRIM(' ' FROM STU_ID))=5)
,STU_NAME VARCHAR2(10) CONSTRAINT STUDENT2_STU_NAME_NN NOT NULL
);

DROP TABLE STUDENT2;

SELECT * FROM STUDENT2;

INSERT INTO STUDENT2 VALUES('A0001','AA');
INSERT INTO STUDENT2 VALUES('A0002','BB');
INSERT INTO STUDENT2 VALUES('A000','BB');

CREATE TABLE SUBJECT2
(SUB_ID NUMBER(3) CONSTRAINT SUBJECT2_SUB_ID_PK PRIMARY KEY
,SUB_NAME VARCHAR2(10) CONSTRAINT SUBJECT2_SUB_NAME_NN NOT NULL
);


SELECT * FROM SUBJECT2;
INSERT INTO SUBJECT2 VALUES('100','A1');

CREATE TABLE SCORE2
(STU_ID CHAR(5) CONSTRAINT SCORE2_STU_ID_NN NOT NULL
,SUB_ID NUMBER(3) CONSTRAINT SCORE2_SUB_ID_NN NOT NULL
,SCORE NUMBER(3) CONSTRAINT SCORE2_SOCRE_NN NOT NULL
,GRADE CHAR(1) CONSTRAINT SCORE2_GRADE_CK CHECK(GRADE IN('A','B','C','D','F'))
,CONSTRAINT SCORE2_PK PRIMARY KEY(STU_ID, SUB_ID)
,CONSTRAINT SCORE2_FK1 FOREIGN KEY(STU_ID) REFERENCES STUDENT2(STU_ID) ON DELETE CASCADE
,CONSTRAINT SCORE2_FK2 FOREIGN KEY(SUB_ID) REFERENCES SUBJECT2(SUB_ID) ON DELETE CASCADE
);

SELECT * FROM SCORE2;
SELECT * FROM SUBJECT2;
SELECT * FROM STUDENT2;

INSERT INTO SCORE2 VALUES('A0001','100','100','A');
INSERT INTO SCORE2 VALUES('A0002','100','85','D');
INSERT INTO SCORE2 VALUES('A0003','100','85','B');
COMMIT;
--DROP TABLE STUDENT2;
--DROP TABLE SUBJECT2;
DROP TABLE SCORE2;

ROLLBACK;
DELETE FROM STUDENT2;
DELETE FROM SUBJECT2;
DELETE FROM SCORE2;



--ERD (Entity Relationship Diagram)
--모델링(설계)
--논리 / 물리(테이블) 