SELECT NAME
     , HEIGHT
     , RANK() OVER(ORDER BY HEIGHT DESC) "RANK"
     , DENSE_RANK() OVER(ORDER BY HEIGHT DESC) "RANK2"
     , ROW_NUMBER() OVER(ORDER BY HEIGHT DESC) "RANK3"
 
 FROM STUDENT
 WHERE HEIGHT > 170
 ORDER BY HEIGHT DESC;

 
SELECT NAME
     , GRADE
     , WEIGHT
     , RANK() OVER(PARTITION BY GRADE ORDER BY WEIGHT DESC) "RANK"
  FROM STUDENT;
  
  
SELECT NAME
     , JUMIN
     , DEPTNO1
     , DECODE(SUBSTR(JUMIN,7,1), '1', 'M', '2', 'W') "MF"
     , WEIGHT 
     , SUM(WEIGHT) OVER(PARTITION BY DEPTNO1, DECODE(SUBSTR(JUMIN,7,1), '1', 'M', '2', 'W') ORDER BY WEIGHT) "TOTAL"
  FROM STUDENT;
  
  
SELECT SUBSTR(EMAIL, INSTR(EMAIL,'@')+1) "DOMAIN"
     , COUNT(*) "SUM_DOMAIN"
     , SUM(COUNT(*)) OVER()
     , COUNT (*) / SUM(COUNT(*)) OVER() * 100
  FROM PROFESSOR
GROUP BY SUBSTR(EMAIL, INSTR(EMAIL,'@')+1)
ORDER BY SUBSTR(EMAIL, INSTR(EMAIL,'@')+1);


SELECT NAME
     , TEL
     , TO_CHAR(PAY, '999,999,999') "PAY"
--     , SUBSTR(TEL, 1, INSTR(TEL,')')-1)
     , TO_CHAR(SUM(PAY) OVER(PARTITION BY SUBSTR(TEL, 1, INSTR(TEL,')')-1)), '999,999,999') "TOTAL_AREA"
     , ROUND(PAY / SUM(PAY) OVER(PARTITION BY SUBSTR(TEL, 1, INSTR(TEL,')')-1))  * 100 , 2) "RATIO"
--     , ROUND(RATIO_TO_REPORT(PAY) OVER(PARTITION BY SUBSTR(TEL, 1, INSTR(TEL,')')-1))*100,2)
 FROM EMP2
 GROUP BY NAME, TEL, PAY;
 
 
CREATE TABLE PROFESSOR2(
PROFNO NUMBER(8),
NAME VARCHAR2(30),
ID VARCHAR2(20),
POSITION VARCHAR2(50),
PAY NUMBER(5),
HIREDATE DATE,
BONUS NUMBER(5),
DEPTNO NUMBER(3),
EMAIL VARCHAR2(100),
HPAGE VARCHAR2(100)
);


CREATE TABLE PROFESSOR3
AS
SELECT PROFNO
     , NAME
     , EMAIL
 FROM PROFESSOR;
SELECT * FROM PROFESSOR3;


ALTER TABLE PROFESSOR3 ADD CARD_YN CHAR(1) DEFAULT 'N';


CREATE TABLE PROFESSOR4
AS
SELECT *
  FROM PROFESSOR3
  WHERE 1=2;
  
  SELECT * FROM PROFESSOR4;
  
  
ALTER TABLE PROFESSOR3 
RENAME COLUMN CARD_YN TO CHECK_CARD_YN;


ALTER TABLE PROFESSOR3 MODIFY EMAIL VARCHAR2(100);

DESC PROFESSOR3;

ALTER TABLE PROFESSOR3 DROP COLUMN CHECK_CARD_YN;